//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahApps.Metro.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColorNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorNames() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MahApps.Metro.Lang.ColorNames", typeof(ColorNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Alice Blue 的本地化字符串。
        /// </summary>
        internal static string AliceBlue {
            get {
                return ResourceManager.GetString("AliceBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Antique White 的本地化字符串。
        /// </summary>
        internal static string AntiqueWhite {
            get {
                return ResourceManager.GetString("AntiqueWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aqua 的本地化字符串。
        /// </summary>
        internal static string Aqua {
            get {
                return ResourceManager.GetString("Aqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aquamarine 的本地化字符串。
        /// </summary>
        internal static string Aquamarine {
            get {
                return ResourceManager.GetString("Aquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Azure 的本地化字符串。
        /// </summary>
        internal static string Azure {
            get {
                return ResourceManager.GetString("Azure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beige 的本地化字符串。
        /// </summary>
        internal static string Beige {
            get {
                return ResourceManager.GetString("Beige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bisque 的本地化字符串。
        /// </summary>
        internal static string Bisque {
            get {
                return ResourceManager.GetString("Bisque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Black 的本地化字符串。
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blanched Almond 的本地化字符串。
        /// </summary>
        internal static string BlanchedAlmond {
            get {
                return ResourceManager.GetString("BlanchedAlmond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue 的本地化字符串。
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue Violet 的本地化字符串。
        /// </summary>
        internal static string BlueViolet {
            get {
                return ResourceManager.GetString("BlueViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Brown 的本地化字符串。
        /// </summary>
        internal static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Burly Wood 的本地化字符串。
        /// </summary>
        internal static string BurlyWood {
            get {
                return ResourceManager.GetString("BurlyWood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cadet Blue 的本地化字符串。
        /// </summary>
        internal static string CadetBlue {
            get {
                return ResourceManager.GetString("CadetBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chartreuse 的本地化字符串。
        /// </summary>
        internal static string Chartreuse {
            get {
                return ResourceManager.GetString("Chartreuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chocolate 的本地化字符串。
        /// </summary>
        internal static string Chocolate {
            get {
                return ResourceManager.GetString("Chocolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coral 的本地化字符串。
        /// </summary>
        internal static string Coral {
            get {
                return ResourceManager.GetString("Coral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cornflower Blue 的本地化字符串。
        /// </summary>
        internal static string CornflowerBlue {
            get {
                return ResourceManager.GetString("CornflowerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cornsilk 的本地化字符串。
        /// </summary>
        internal static string Cornsilk {
            get {
                return ResourceManager.GetString("Cornsilk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Crimson 的本地化字符串。
        /// </summary>
        internal static string Crimson {
            get {
                return ResourceManager.GetString("Crimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Blue 的本地化字符串。
        /// </summary>
        internal static string DarkBlue {
            get {
                return ResourceManager.GetString("DarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Cyan 的本地化字符串。
        /// </summary>
        internal static string DarkCyan {
            get {
                return ResourceManager.GetString("DarkCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Goldenrod 的本地化字符串。
        /// </summary>
        internal static string DarkGoldenrod {
            get {
                return ResourceManager.GetString("DarkGoldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Gray 的本地化字符串。
        /// </summary>
        internal static string DarkGray {
            get {
                return ResourceManager.GetString("DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Green 的本地化字符串。
        /// </summary>
        internal static string DarkGreen {
            get {
                return ResourceManager.GetString("DarkGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Khaki 的本地化字符串。
        /// </summary>
        internal static string DarkKhaki {
            get {
                return ResourceManager.GetString("DarkKhaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Magenta 的本地化字符串。
        /// </summary>
        internal static string DarkMagenta {
            get {
                return ResourceManager.GetString("DarkMagenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Olive Green 的本地化字符串。
        /// </summary>
        internal static string DarkOliveGreen {
            get {
                return ResourceManager.GetString("DarkOliveGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Orange 的本地化字符串。
        /// </summary>
        internal static string DarkOrange {
            get {
                return ResourceManager.GetString("DarkOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Orchid 的本地化字符串。
        /// </summary>
        internal static string DarkOrchid {
            get {
                return ResourceManager.GetString("DarkOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Red 的本地化字符串。
        /// </summary>
        internal static string DarkRed {
            get {
                return ResourceManager.GetString("DarkRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Salmon 的本地化字符串。
        /// </summary>
        internal static string DarkSalmon {
            get {
                return ResourceManager.GetString("DarkSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Sea Green 的本地化字符串。
        /// </summary>
        internal static string DarkSeaGreen {
            get {
                return ResourceManager.GetString("DarkSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Slate Blue 的本地化字符串。
        /// </summary>
        internal static string DarkSlateBlue {
            get {
                return ResourceManager.GetString("DarkSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Slate Gray 的本地化字符串。
        /// </summary>
        internal static string DarkSlateGray {
            get {
                return ResourceManager.GetString("DarkSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Turquoise 的本地化字符串。
        /// </summary>
        internal static string DarkTurquoise {
            get {
                return ResourceManager.GetString("DarkTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Violet 的本地化字符串。
        /// </summary>
        internal static string DarkViolet {
            get {
                return ResourceManager.GetString("DarkViolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deep Pink 的本地化字符串。
        /// </summary>
        internal static string DeepPink {
            get {
                return ResourceManager.GetString("DeepPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deep Sky Blue 的本地化字符串。
        /// </summary>
        internal static string DeepSkyBlue {
            get {
                return ResourceManager.GetString("DeepSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dim Gray 的本地化字符串。
        /// </summary>
        internal static string DimGray {
            get {
                return ResourceManager.GetString("DimGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dodger Blue 的本地化字符串。
        /// </summary>
        internal static string DodgerBlue {
            get {
                return ResourceManager.GetString("DodgerBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firebrick 的本地化字符串。
        /// </summary>
        internal static string Firebrick {
            get {
                return ResourceManager.GetString("Firebrick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Floral White 的本地化字符串。
        /// </summary>
        internal static string FloralWhite {
            get {
                return ResourceManager.GetString("FloralWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forest Green 的本地化字符串。
        /// </summary>
        internal static string ForestGreen {
            get {
                return ResourceManager.GetString("ForestGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fuchsia 的本地化字符串。
        /// </summary>
        internal static string Fuchsia {
            get {
                return ResourceManager.GetString("Fuchsia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gainsboro 的本地化字符串。
        /// </summary>
        internal static string Gainsboro {
            get {
                return ResourceManager.GetString("Gainsboro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ghost White 的本地化字符串。
        /// </summary>
        internal static string GhostWhite {
            get {
                return ResourceManager.GetString("GhostWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gold 的本地化字符串。
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goldenrod 的本地化字符串。
        /// </summary>
        internal static string Goldenrod {
            get {
                return ResourceManager.GetString("Goldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gray 的本地化字符串。
        /// </summary>
        internal static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Green 的本地化字符串。
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Green Yellow 的本地化字符串。
        /// </summary>
        internal static string GreenYellow {
            get {
                return ResourceManager.GetString("GreenYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Honeydew 的本地化字符串。
        /// </summary>
        internal static string Honeydew {
            get {
                return ResourceManager.GetString("Honeydew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hot Pink 的本地化字符串。
        /// </summary>
        internal static string HotPink {
            get {
                return ResourceManager.GetString("HotPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indian Red 的本地化字符串。
        /// </summary>
        internal static string IndianRed {
            get {
                return ResourceManager.GetString("IndianRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indigo 的本地化字符串。
        /// </summary>
        internal static string Indigo {
            get {
                return ResourceManager.GetString("Indigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ivory 的本地化字符串。
        /// </summary>
        internal static string Ivory {
            get {
                return ResourceManager.GetString("Ivory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Khaki 的本地化字符串。
        /// </summary>
        internal static string Khaki {
            get {
                return ResourceManager.GetString("Khaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lavender 的本地化字符串。
        /// </summary>
        internal static string Lavender {
            get {
                return ResourceManager.GetString("Lavender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lavender Blush 的本地化字符串。
        /// </summary>
        internal static string LavenderBlush {
            get {
                return ResourceManager.GetString("LavenderBlush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lawn Green 的本地化字符串。
        /// </summary>
        internal static string LawnGreen {
            get {
                return ResourceManager.GetString("LawnGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lemon Chiffon 的本地化字符串。
        /// </summary>
        internal static string LemonChiffon {
            get {
                return ResourceManager.GetString("LemonChiffon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Blue 的本地化字符串。
        /// </summary>
        internal static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LightCoral 的本地化字符串。
        /// </summary>
        internal static string LightCoral {
            get {
                return ResourceManager.GetString("LightCoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Cyan 的本地化字符串。
        /// </summary>
        internal static string LightCyan {
            get {
                return ResourceManager.GetString("LightCyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Goldenrod Yellow 的本地化字符串。
        /// </summary>
        internal static string LightGoldenrodYellow {
            get {
                return ResourceManager.GetString("LightGoldenrodYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Gray 的本地化字符串。
        /// </summary>
        internal static string LightGray {
            get {
                return ResourceManager.GetString("LightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Green 的本地化字符串。
        /// </summary>
        internal static string LightGreen {
            get {
                return ResourceManager.GetString("LightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Pink 的本地化字符串。
        /// </summary>
        internal static string LightPink {
            get {
                return ResourceManager.GetString("LightPink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Salmon 的本地化字符串。
        /// </summary>
        internal static string LightSalmon {
            get {
                return ResourceManager.GetString("LightSalmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Sea Green 的本地化字符串。
        /// </summary>
        internal static string LightSeaGreen {
            get {
                return ResourceManager.GetString("LightSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Sky Blue 的本地化字符串。
        /// </summary>
        internal static string LightSkyBlue {
            get {
                return ResourceManager.GetString("LightSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Slate Gray 的本地化字符串。
        /// </summary>
        internal static string LightSlateGray {
            get {
                return ResourceManager.GetString("LightSlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Steel Blue 的本地化字符串。
        /// </summary>
        internal static string LightSteelBlue {
            get {
                return ResourceManager.GetString("LightSteelBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Yellow 的本地化字符串。
        /// </summary>
        internal static string LightYellow {
            get {
                return ResourceManager.GetString("LightYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lime 的本地化字符串。
        /// </summary>
        internal static string Lime {
            get {
                return ResourceManager.GetString("Lime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lime Green 的本地化字符串。
        /// </summary>
        internal static string LimeGreen {
            get {
                return ResourceManager.GetString("LimeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linen 的本地化字符串。
        /// </summary>
        internal static string Linen {
            get {
                return ResourceManager.GetString("Linen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maroon 的本地化字符串。
        /// </summary>
        internal static string Maroon {
            get {
                return ResourceManager.GetString("Maroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium Aquamarine 的本地化字符串。
        /// </summary>
        internal static string MediumAquamarine {
            get {
                return ResourceManager.GetString("MediumAquamarine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium Blue 的本地化字符串。
        /// </summary>
        internal static string MediumBlue {
            get {
                return ResourceManager.GetString("MediumBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium Orchid 的本地化字符串。
        /// </summary>
        internal static string MediumOrchid {
            get {
                return ResourceManager.GetString("MediumOrchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium Purple 的本地化字符串。
        /// </summary>
        internal static string MediumPurple {
            get {
                return ResourceManager.GetString("MediumPurple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium Sea Green 的本地化字符串。
        /// </summary>
        internal static string MediumSeaGreen {
            get {
                return ResourceManager.GetString("MediumSeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium Slate Blue 的本地化字符串。
        /// </summary>
        internal static string MediumSlateBlue {
            get {
                return ResourceManager.GetString("MediumSlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium Spring Green 的本地化字符串。
        /// </summary>
        internal static string MediumSpringGreen {
            get {
                return ResourceManager.GetString("MediumSpringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium Turquoise 的本地化字符串。
        /// </summary>
        internal static string MediumTurquoise {
            get {
                return ResourceManager.GetString("MediumTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium Violet Red 的本地化字符串。
        /// </summary>
        internal static string MediumVioletRed {
            get {
                return ResourceManager.GetString("MediumVioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Midnight Blue 的本地化字符串。
        /// </summary>
        internal static string MidnightBlue {
            get {
                return ResourceManager.GetString("MidnightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mint Cream 的本地化字符串。
        /// </summary>
        internal static string MintCream {
            get {
                return ResourceManager.GetString("MintCream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Misty Rose 的本地化字符串。
        /// </summary>
        internal static string MistyRose {
            get {
                return ResourceManager.GetString("MistyRose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moccasin 的本地化字符串。
        /// </summary>
        internal static string Moccasin {
            get {
                return ResourceManager.GetString("Moccasin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navajo White 的本地化字符串。
        /// </summary>
        internal static string NavajoWhite {
            get {
                return ResourceManager.GetString("NavajoWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navy 的本地化字符串。
        /// </summary>
        internal static string Navy {
            get {
                return ResourceManager.GetString("Navy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Old Lace 的本地化字符串。
        /// </summary>
        internal static string OldLace {
            get {
                return ResourceManager.GetString("OldLace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Olive 的本地化字符串。
        /// </summary>
        internal static string Olive {
            get {
                return ResourceManager.GetString("Olive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Olive Drab 的本地化字符串。
        /// </summary>
        internal static string OliveDrab {
            get {
                return ResourceManager.GetString("OliveDrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orange 的本地化字符串。
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orange Red 的本地化字符串。
        /// </summary>
        internal static string OrangeRed {
            get {
                return ResourceManager.GetString("OrangeRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Orchid 的本地化字符串。
        /// </summary>
        internal static string Orchid {
            get {
                return ResourceManager.GetString("Orchid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pale Goldenrod 的本地化字符串。
        /// </summary>
        internal static string PaleGoldenrod {
            get {
                return ResourceManager.GetString("PaleGoldenrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pale Green 的本地化字符串。
        /// </summary>
        internal static string PaleGreen {
            get {
                return ResourceManager.GetString("PaleGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pale Turquoise 的本地化字符串。
        /// </summary>
        internal static string PaleTurquoise {
            get {
                return ResourceManager.GetString("PaleTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pale Violet Red 的本地化字符串。
        /// </summary>
        internal static string PaleVioletRed {
            get {
                return ResourceManager.GetString("PaleVioletRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Papaya Whip 的本地化字符串。
        /// </summary>
        internal static string PapayaWhip {
            get {
                return ResourceManager.GetString("PapayaWhip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peach Puff 的本地化字符串。
        /// </summary>
        internal static string PeachPuff {
            get {
                return ResourceManager.GetString("PeachPuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peru 的本地化字符串。
        /// </summary>
        internal static string Peru {
            get {
                return ResourceManager.GetString("Peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pink 的本地化字符串。
        /// </summary>
        internal static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plum 的本地化字符串。
        /// </summary>
        internal static string Plum {
            get {
                return ResourceManager.GetString("Plum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powder Blue 的本地化字符串。
        /// </summary>
        internal static string PowderBlue {
            get {
                return ResourceManager.GetString("PowderBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purple 的本地化字符串。
        /// </summary>
        internal static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red 的本地化字符串。
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rosy Brown 的本地化字符串。
        /// </summary>
        internal static string RosyBrown {
            get {
                return ResourceManager.GetString("RosyBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Royal Blue 的本地化字符串。
        /// </summary>
        internal static string RoyalBlue {
            get {
                return ResourceManager.GetString("RoyalBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saddle Brown 的本地化字符串。
        /// </summary>
        internal static string SaddleBrown {
            get {
                return ResourceManager.GetString("SaddleBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Salmon 的本地化字符串。
        /// </summary>
        internal static string Salmon {
            get {
                return ResourceManager.GetString("Salmon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sandy Brown 的本地化字符串。
        /// </summary>
        internal static string SandyBrown {
            get {
                return ResourceManager.GetString("SandyBrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sea Green 的本地化字符串。
        /// </summary>
        internal static string SeaGreen {
            get {
                return ResourceManager.GetString("SeaGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sea Shell 的本地化字符串。
        /// </summary>
        internal static string SeaShell {
            get {
                return ResourceManager.GetString("SeaShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sienna 的本地化字符串。
        /// </summary>
        internal static string Sienna {
            get {
                return ResourceManager.GetString("Sienna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Silver 的本地化字符串。
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sky Blue 的本地化字符串。
        /// </summary>
        internal static string SkyBlue {
            get {
                return ResourceManager.GetString("SkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slate Blue 的本地化字符串。
        /// </summary>
        internal static string SlateBlue {
            get {
                return ResourceManager.GetString("SlateBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slate Gray 的本地化字符串。
        /// </summary>
        internal static string SlateGray {
            get {
                return ResourceManager.GetString("SlateGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snow 的本地化字符串。
        /// </summary>
        internal static string Snow {
            get {
                return ResourceManager.GetString("Snow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spring Green 的本地化字符串。
        /// </summary>
        internal static string SpringGreen {
            get {
                return ResourceManager.GetString("SpringGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Steel Blue 的本地化字符串。
        /// </summary>
        internal static string SteelBlue {
            get {
                return ResourceManager.GetString("SteelBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tan 的本地化字符串。
        /// </summary>
        internal static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teal 的本地化字符串。
        /// </summary>
        internal static string Teal {
            get {
                return ResourceManager.GetString("Teal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thistle 的本地化字符串。
        /// </summary>
        internal static string Thistle {
            get {
                return ResourceManager.GetString("Thistle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tomato 的本地化字符串。
        /// </summary>
        internal static string Tomato {
            get {
                return ResourceManager.GetString("Tomato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transparent 的本地化字符串。
        /// </summary>
        internal static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Turquoise 的本地化字符串。
        /// </summary>
        internal static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Violet 的本地化字符串。
        /// </summary>
        internal static string Violet {
            get {
                return ResourceManager.GetString("Violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wheat 的本地化字符串。
        /// </summary>
        internal static string Wheat {
            get {
                return ResourceManager.GetString("Wheat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White 的本地化字符串。
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White Smoke 的本地化字符串。
        /// </summary>
        internal static string WhiteSmoke {
            get {
                return ResourceManager.GetString("WhiteSmoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yellow 的本地化字符串。
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yellow Green 的本地化字符串。
        /// </summary>
        internal static string YellowGreen {
            get {
                return ResourceManager.GetString("YellowGreen", resourceCulture);
            }
        }
    }
}
